### ISSUE TITLE
ModuleNotFoundError: No module named 'context_locals'

### ISSUE THREAD

**Issue by emptykk** [datawhalechina/llm-cookbook#150]
按照教程配的环境，在[1.1 使用分隔符清晰地表示输入的不同部分](https://datawhalechina.github.io/llm-cookbook/#/C1/2.%20%E6%8F%90%E7%A4%BA%E5%8E%9F%E5%88%99%20Guidelines?id=_11-%e4%bd%bf%e7%94%a8%e5%88%86%e9%9a%94%e7%ac%a6%e6%b8%85%e6%99%b0%e5%9c%b0%e8%a1%a8%e7%a4%ba%e8%be%93%e5%85%a5%e7%9a%84%e4%b8%8d%e5%90%8c%e9%83%a8%e5%88%86)  `from tool import get_completion
`就出现了问题

**Comment by logan-zou** [comment]
您好，在线文档为了阅读的流畅性，将工具函数进行了本地封装；如需要复现，建议下载 notebook 文件夹中的代码
