### ISSUE TITLE
必修三第7个文档代理

### ISSUE THREAD

**Issue by lzhzzzzwill** [datawhalechina/llm-cookbook#151]
当我运行
from langchain.agents.agent_toolkits import create_python_agent
from langchain.tools.python.tool import PythonREPLTool时都出现了报错。
第一个的报错是langchain/agents/agent_toolkits' does not start with /langchain_core'
第二个是no module。
目前我解决了第二个，现在的调用应该是改成了from langchain_experimental.tools import PythonREPLTool。
但是第一个的错误还是无法解决。

**Comment by logan-zou** [comment]
您好，该问题可能是由于环境依赖包不一致，我们正在计划更新现有代码到最新的依赖～
