### ISSUE TITLE
from tool import get_completion

### ISSUE THREAD

**Issue by windrunner0** [datawhalechina/llm-cookbook#160]
python3.9遇到如下问题
File /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tool/__init__.py:11
      1 # -*- coding: utf-8 -*-
      2 #
      3 #  Copyright (c) 2009—2010 Andrey Mikhailenko and contributors
   (...)
      9 #  Software Foundation. See the file README for copying conditions.
     10 #
---> 11 from context_locals import app, local
     12 from application import Application, WebApplication #, current_app as app
     15 __all__ = ['Application', 'WebApplication', 'app', 'local']

ModuleNotFoundError: No module named 'context_locals'

**Comment by logan-zou** [comment]
建议使用 content 目录下的 notebook 文件进行代码复现，docs 和在线阅读为了阅读体验对代码做了封装
